### PR TITLE
added options for: colors, hiding, sha1 length, orientation, git dir, etc.

### PR DESCRIPTION
**Pull request by ndoss**
Made a bunch of miscellaneous changes (not sure I like how I did some things, e.g. color schemes) so I thought I'd let you know about them.    I wanted more control over what was displayed for use with tutorials.    Video:   https://www.youtube.com/watch?v=xz8oLPuLxok

By the way, nice tool!  Thanks!

### CODE REVIEW

**Comment by sensorflo** [comment]
Sorry for the late reply. I had a long holliday this summer and I did not check my projects. I like your changes and will split them into smaller changes and then merge or rebase them into master.

**Comment by sensorflo** [comment]
Thanks again for your great changes.  I broke them into smaller commits and made a few changes:
- Added a color scheme named 'default' which uses the colors before your changes.  The default color scheme is naturally consequently the color scheme named 'default'.
- Removed the trailing "[...]" (e.g. [$GIT_DIR]) from the usage text.  I think this is no useful information for a user who just wants to use the git-draw tool; it might only be useful for a user who wants to edit the git-draw script. Or do I misunderstand something here?
- For options having an argument, made a simple check if its valid.
- If echo is used to print an error, print to stderr
- White space changes, a few re-wordings.

All these commits have you as the author despite I didn't overtook them 100% as is.  I hope you're fine with that.  I pushed the commits to my github repository using the `temporary' branch ndoss.  This way you can object if you're not happy with the changes I made in your name.  When you're fine with them I merge them into master.

I didn't yet overtook the git-draw-watch script.

**Comment by ndoss** [comment]
My apologies for taking so long to respond, I'm been on vacation for the
last couple of weeks.

> When you're fine with them I merge them into master.

They look great.

> All these commits have you as the author despite I didn't overtook them
> 100% as is. I hope you're fine with that.

More than fine!

--ND

**Comment by sensorflo** [comment]
Merged the ndoss branch by fast forwarding master, then deleted the ndoss branch. Thanks again for your help.

**Pull request closed without merging**
